IBM- PNT2022TMID33204- Deep Learning Fundus Image Analysis For Early Detection Of Diabetic Retinopathy

In [ ]:
#import load_model class for loading h5 file
from tensorflow.keras.models import load_model
#import image class to process the images
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.inception_v3 import preprocess_input
import numpy as np

In [ ]:
model=load_model('updated-xception-diabetic-retinopathy.h5')

In [ ]:
img=image.load_img(r'/Drive/MyDrive/ibm/preprocessed dataset/preprocessed dataset/testing/0/cfb17a7cc8d4.png',target_size=(299,299))

In [ ]:
x=image.img_to_array(img)

In [ ]:
import matplotlib.pyplot as plt
x.shape

(299, 299, 3)

In [ ]:
import numpy as np
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 299, 299, 3)

In [ ]:
model.predict(img_data)

1/1 [==============================] - 1s 1s/step


array([[1.0000000e+00, 1.3992481e-20, 2.4709993e-12, 1.2183851e-20,
        9.3386634e-19]], dtype=float32)

In [ ]:
output=np.argmax(model.predict(img_data), axis=1)

1/1 [==============================] - 0s 22ms/step


In [ ]:
output==0,output==1,output==2,output==3,output==4

(array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]))

In [ ]:
index=['No Diabetic Retinopathy', 'Mild DR', 'Moderate DR', 'Severe DR', 'Proliferative DR']
result = str(index[output[0]])
result

'No Diabetic Retinopathy'